server:
  port: 8080

# DB접속 정보
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootclass?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: bootuser
    password: 1234
  # cache값을 사용하지 않겠다는 의미
  thymeleaf:
    cache: false

  # JPA 관련 설정, datasource: 위치와 같은 위치에 작성해줘야함.
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
      # create : 실행할 때 마다 전체 재시작
      # update : 실행할 때 table drop 없이 실행.